logging:
  level:
    org:
      apache:
        kafka:
          clients:
            NetworkClient: off
    org.hibernate:
      sql: debug
      orm.jdbc.bind: trace
spring:
  application.name: ecommerce
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/ecommerce
    username: ecommerce
    password: aa
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  data:
    web:
      pageable:
        one-indexed-parameters: true
        max-page-size: 50
        default-page-size: 10
    redis:
      host: localhost
      port: 6379
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: payment-group
      auto-offset-reset: earliest

springdoc:
  packages-to-scan: io.hhplus.ecommerce
  default-consumes-media-type: application/json;charset=UTF-8
  default-produces-media-type: application/json;charset=UTF-8
  cache.disabled: true

  api-docs:
    path: /api-docs/json
    groups:
      enabled: true
    swagger-ui:
      enabled: true
      path: /docs
      tags-sorter: alpha
      operations-sorter: alpha

cors:
  allowed-origins: http://localhost:3000,http://localhost:4000

outbox:
  max-batch-count: 10
  batch-size: 50
  kafka-timeout-seconds: 3
  max-retry-count: 3
